---
all:
  children:
    ceos:
      children:
        spine:
          hosts:
            spine01:
              ansible_host: 172.20.20.11
            spine02:
              ansible_host: 172.20.20.12
        leaf:
          hosts:
            leaf01:
              ansible_host: 172.20.20.21
            leaf02:
              ansible_host: 172.20.20.22
            leaf03:
              ansible_host: 172.20.20.23
            leaf04:
              ansible_host: 172.20.20.24
