name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-fabric:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: |
          uv sync --locked --all-extras --dev
          uv pip install -e .

      - name: Run unit tests
        run: uv run pytest tests/unit/

      - name: Install ContainerLab
        run: curl -sL https://containerlab.dev/setup | sudo -E bash -s "all"

      - name: Deploy ContainerLab topology
        run: |
          cd containerlab/
          containerlab deploy

      - name: Deploy configurations
        run: |
          cd ansible/
          uv run ansible-playbook playbooks/deploy.yml -i inventory.dev.yml

      - name: Run fabric tests
        run: uv run pytest tests/fabric/
