name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  deploy-fabric:
    environment: Production
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: |
          uv sync --locked --all-extras --dev
          uv pip install -e .

      # using containerlab as production environment at this time
      - name: Install containerlab
        run: curl -sL https://containerlab.dev/setup | sudo -E bash -s "all"

      - name: Cleanup existing production topology
        run: |
          cd containerlab-prod/
          containerlab destroy || true

      - name: Deploy production topology
        run: |
          cd containerlab-prod/
          containerlab deploy

      - name: Deploy configurations
        run: |
          cd ansible/
          uv run ansible-playbook playbooks/deploy.yml -i inventory.prod.yml

      - name: Cleanup current production topology
        run: |
          cd containerlab-prod/
          containerlab destroy
